/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CameraRouteImport } from './routes/camera'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PeopleIndexRouteImport } from './routes/people.index'
import { Route as PeopleIdRouteImport } from './routes/people.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CameraRoute = CameraRouteImport.update({
  id: '/camera',
  path: '/camera',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleIndexRoute = PeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleIdRoute = PeopleIdRouteImport.update({
  id: '/people/$id',
  path: '/people/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/camera': typeof CameraRoute
  '/payments': typeof PaymentsRoute
  '/settings': typeof SettingsRoute
  '/people/$id': typeof PeopleIdRoute
  '/people/': typeof PeopleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/camera': typeof CameraRoute
  '/payments': typeof PaymentsRoute
  '/settings': typeof SettingsRoute
  '/people/$id': typeof PeopleIdRoute
  '/people': typeof PeopleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/camera': typeof CameraRoute
  '/payments': typeof PaymentsRoute
  '/settings': typeof SettingsRoute
  '/people/$id': typeof PeopleIdRoute
  '/people/': typeof PeopleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/camera' | '/payments' | '/settings' | '/people/$id' | '/people/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/camera' | '/payments' | '/settings' | '/people/$id' | '/people'
  id:
    | '__root__'
    | '/'
    | '/camera'
    | '/payments'
    | '/settings'
    | '/people/$id'
    | '/people/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CameraRoute: typeof CameraRoute
  PaymentsRoute: typeof PaymentsRoute
  SettingsRoute: typeof SettingsRoute
  PeopleIdRoute: typeof PeopleIdRoute
  PeopleIndexRoute: typeof PeopleIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camera': {
      id: '/camera'
      path: '/camera'
      fullPath: '/camera'
      preLoaderRoute: typeof CameraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/': {
      id: '/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof PeopleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/$id': {
      id: '/people/$id'
      path: '/people/$id'
      fullPath: '/people/$id'
      preLoaderRoute: typeof PeopleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CameraRoute: CameraRoute,
  PaymentsRoute: PaymentsRoute,
  SettingsRoute: SettingsRoute,
  PeopleIdRoute: PeopleIdRoute,
  PeopleIndexRoute: PeopleIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
